version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "8002:6379"
    networks:
      - redis-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

  zookeeper:
    image: zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      - mom_network

networks:
  mom_network:
    driver: bridge
