version: '3.8'

services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client1
    restart: always
    networks:
      - client-network
    # volumes:
    #   - ./client1/app:/app
    #   - ./client1/config.yaml:/app/config.yaml
    # command: >
    #   sh -c "cp /app/config.yaml /app/src/config.yaml && python -m src.main"

networks:
  client-network:
    driver: bridge