version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

  mom-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mom-server
    restart: always
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - redis-network

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge
