version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

  redis2:
    image: redis:alpine
    container_name: redis2
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis2_data:/data
    networks:
      - redis-network
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
volumes:
  redis2_data: 
    driver: local
  redis_data: 
    driver: local

networks:
  redis-network:
    driver: bridge