name: Pylint Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pylint-server:
    name: Run Pylint Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: Install dependencies
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        working-directory: server
        run: pylint --rcfile=.pylintrc app/
